name-template: 'Release $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '📈 Analytics & Data'
    labels:
      - 'analytics'
      - 'visualization'
      - 'database'

  - title: '🎨 UI/UX Improvements'
    labels:
      - 'ui'

  - title: '🏗️ Infrastructure & Performance'
    labels:
      - 'infrastructure'
      - 'performance'
      - 'build'

  - title: '🔄 Code Quality & Refactoring'
    labels:
      - 'refactor'
      - 'testing'

  - title: '🔒 Security & Compliance'
    labels:
      - 'security'

  - title: '📝 Documentation'
    labels:
      - 'documentation'

  - title: '📦 Dependencies'
    labels:
      - 'dependencies'

  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

exclude-labels:
  - 'skip-changelog'

template: |
  # Highlights
  $CHANGES

  ## Security Compliance
  [![SLSA 3](https://slsa.dev/images/gh-badge-level3.svg)](https://github.com/Hack23/cia-compliance-manager/attestations/)

  ## Contributors
  Thanks to $CONTRIBUTORS for their contributions to this release!

  **Full Changelog**: https://github.com/Hack23/cia-compliance-manager/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'security'
      - 'dependencies'
  default: patch

autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\([^)]+\))?:/i'
  - label: 'bug'
    title:
      - '/^fix(\([^)]+\))?:/i'
  - label: 'documentation'
    title:
      - '/^docs(\([^)]+\))?:/i'
  - label: 'enhancement'
    title:
      - '/^enhance(\([^)]+\))?:/i'
  - label: 'dependencies'
    title:
      - '/^build\(deps\):/i'
  - label: 'security'
    title:
      - '/^security(\([^)]+\))?:/i'
  - label: 'performance'
    title:
      - '/^perf(\([^)]+\))?:/i'
  - label: 'refactor'
    title:
      - '/^refactor(\([^)]+\))?:/i'
