name: Generate Enhanced Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "src/**"
      - "*.json"
      - "docs/**"
      - ".github/workflows/documentation.yml"

permissions:
  contents: read

jobs:
  build-docs:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install GraphViz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      # Run tests with coverage
      - name: Run tests with coverage
        run: npm run coverage

      # Create coverage directory in docs
      - name: Prepare coverage directory
        run: mkdir -p docs/coverage docs/dependencies

      # Run tests with coverage
      - name: Generate Coverage
        run: npm run coverage

      - name: Generate API documentation
        run: npm run docs || echo "API docs generation failed - continuing"

      - name: Generate UML diagrams
        run: npm run docs:uml || echo "UML diagram generation failed - continuing"

      - name: Generate dependency diagrams
        run: npm run docs:dependencies || echo "Dependency diagram generation failed - continuing"

      - name: Generate architecture diagrams
        run: npm run docs:architecture || echo "Architecture diagram generation failed - continuing"


      - name: Create combined index page
        run: |
          cat > docs/documentation.html << EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>CIA Compliance Manager Documentation</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 1100px;
                margin: 0 auto;
                padding: 20px;
              }
              header {
                text-align: center;
                margin-bottom: 2rem;
                padding-bottom: 1rem;
                border-bottom: 1px solid #eaeaea;
              }
              h1 { margin-top: 0; color: #0366d6; }
              h2 { color: #0366d6; margin-top: 2rem; }
              .cards {
                display: grid;
                grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
                gap: 1rem;
              }
              .card {
                border: 1px solid #e1e4e8;
                border-radius: 6px;
                padding: 1.5rem;
                background: white;
                box-shadow: 0 1px 3px rgba(0,0,0,0.12);
                transition: transform 0.3s ease, box-shadow 0.3s ease;
              }
              .card:hover {
                transform: translateY(-4px);
                box-shadow: 0 5px 15px rgba(0,0,0,0.1);
              }
              .card h3 {
                margin-top: 0;
                margin-bottom: 1rem;
                color: #0366d6;
              }
              .card p {
                margin-bottom: 1rem;
                color: #586069;
              }
              .card a {
                display: inline-block;
                padding: 0.5rem 1rem;
                border-radius: 4px;
                background: #0366d6;
                color: white;
                text-decoration: none;
              }
              .card a:hover {
                background: #024ea4;
              }
              footer {
                margin-top: 3rem;
                padding-top: 1rem;
                border-top: 1px solid #eaeaea;
                text-align: center;
                font-size: 0.9rem;
                color: #586069;
              }
            </style>
          </head>
          <body>
            <header>
              <h1>CIA Compliance Manager Documentation</h1>
              <p>Comprehensive documentation for the CIA (Confidentiality, Integrity, Availability) Compliance Manager</p>
            </header>
            
            <div class="cards">
              <div class="card">
                <h3>API Documentation</h3>
                <p>Detailed API reference for all components, types, and functions used in the application.</p>
                <a href="https://github.com/Hack23/cia-compliance-manager/blob/main/docs/api/globals.md">View API Docs</a>
              </div>
              
              <div class="card">
                <h3>Diagrams</h3>
                <p>UML and Mermaid diagrams showing the relationships between core types and components.</p>
                <a href="https://github.com/Hack23/cia-compliance-manager/blob/main/docs/diagrams/modules.md">View Diagrams</a>
              </div>
              
              <div class="card">
                <h3>Architecture</h3>
                <p>System architecture diagrams showing module dependencies and component relationships.</p>
                <a href="https://github.com/Hack23/cia-compliance-manager/blob/main/docs/architecture/ARCHITECTURE.md">View Architecture</a>
              </div>
              
              <div class="card">
                <h3>Code Coverage</h3>
                <p>Test coverage reports showing how much of the codebase is covered by tests.</p>
                <a href="https://hack23.github.io/cia-compliance-manager/coverage/index.html">View Coverage Report</a>
              </div>
              
              <div class="card">
                <h3>Dependencies</h3>
                <p>Visual representation of module dependencies throughout the codebase.</p>
                <a href="https://hack23.github.io/cia-compliance-manager/dependencies/module-dependencies.svg">View Dependencies</a>
              </div>
              
              <div class="card">
                <h3>Markdown Docs</h3>
                <p>API documentation in Markdown format for easy integration with other tools.</p>
                <a href="https://github.com/Hack23/cia-compliance-manager/blob/main/docs/markdown/modules.md">View Markdown</a>
              </div>
              
              <div class="card">
                <h3>Project Architecture</h3>
                <p>C4 model diagrams and other architectural documentation.</p>
                <a href="https://github.com/Hack23/cia-compliance-manager/blob/main/docs/architecture/ARCHITECTURE.md">View Architecture</a>
              </div>
            </div>
            
            <h2>Documentation Overview</h2>
            <p>
              This documentation is automatically generated from the source code and documentation files in the repository.
              It includes API reference, type definitions, architecture diagrams, and more to help you understand the
              CIA Compliance Manager codebase.
            </p>

            <footer>
              <p>Generated on $(date) | <a href="https://github.com/Hack23/cia-compliance-manager">GitHub Repository</a></p>
            </footer>
          </body>
          </html>
          EOF

      - name: Archive documentation artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: documentation
          path: docs/
          retention-days: 7

      # Only deploy on push to main, not PRs
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: docs
          branch: main
          clean: false
