name: PR Documentation Preview

on:
  workflow_run:
    workflows: ["Generate Enhanced Documentation"]
    types:
      - completed

jobs:
  pr-preview:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Download documentation artifact
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });

            const matchArtifact = artifacts.data.artifacts.find(artifact => artifact.name === "documentation");
            if (!matchArtifact) {
              throw new Error('Documentation artifact not found');
            }

            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip'
            });

            const fs = require('fs');
            fs.writeFileSync('docs.zip', Buffer.from(download.data));

            await exec.exec('unzip', ['-o', 'docs.zip', '-d', 'docs']);

      - name: Extract PR number
        uses: actions/github-script@v7
        id: pr-number
        with:
          script: |
            const runDetailsResponse = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });

            // Extract PR number from the workflow run
            const prNumber = runDetailsResponse.data.pull_requests[0]?.number;
            if (!prNumber) {
              return null;
            }

            return prNumber;
          result-encoding: string

      - name: Comment on PR with preview link
        if: steps.pr-number.outputs.result != 'null'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr-number.outputs.result }};
            const runId = ${{ github.run_id }};

            const comment = `
            ## 📚 Documentation Preview

            Documentation has been generated for this PR! You can preview it here:

            - [API Documentation](https://github.com/${{ github.repository }}/actions/runs/${runId}/artifacts)
            - [UML Diagrams](https://github.com/${{ github.repository }}/actions/runs/${runId}/artifacts)
            - [Architecture Diagrams](https://github.com/${{ github.repository }}/actions/runs/${runId}/artifacts)

            > Note: You'll need to download the artifacts to view them locally, as artifact previews aren't available directly.
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
